### ISSUE TITLE
doesn't work with nuxt

### ISSUE THREAD

**Issue by CavalcanteLeo** [kempsteven/vue-html2pdf#12]
plugin:
```
import Vue from 'vue'
import VueHtml2pdf from 'vue-html2pdf'
Vue.use(VueHtml2pdf)
```

nuxt.config.js
```
  plugins: [
    '@/plugins/antd-ui',
    { src: '@/plugins/vue-apexcharts', ssr: false },
    { src: '@/plugins/vue-html2pdf', ssr: false }
  ]
```

somehow, sometimes works but most of the time the page freezes, and sometimes shows an error: window is not defined, even i use <no-ssr>

**Comment by kempsteven** [comment]
Hey searched a bit and this might be the case: https://stackoverflow.com/questions/54979644/window-is-not-defined-in-nuxt-js
I will also try and reproduce it on a nuxt project

**Comment by kempsteven** [comment]
So I reproduced it, and find a way to fix it.

**First on your nuxt.config.js:**
just add `mode: 'client'`
```
...
plugins: [
    { src: '@/plugins/vue-html2pdf', mode: 'client' }
],
...
```

**Documentation**: https://nuxtjs.org/guide/plugins#client-or-server-side-only

So when you did that you will get an error:
`[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.`

You will have to wrap your component on a `client-only` component to fix that:
```
<client-only>
   <vue-html2pdf
        :show-layout="true"
        :enable-download="true"
        :preview-modal="true"
        :paginate-elements-by-height="1400"
        filename="hee hee"
        :pdf-quality="2"
        pdf-format="a4"
        pdf-orientation="landscape"
        pdf-content-width="800px"
 
        @progress="onProgress($event)"
        @hasStartedGeneration="hasStartedGeneration()"
        @hasGenerated="hasGenerated($event)"
        ref="html2Pdf"
      >
        <section slot="pdf-content">
          asdasdasdasd
        </section>
   </vue-html2pdf>
</client-only>
```

Here is the documentation of `client-only` :
https://nuxtjs.org/api/components-client-only/

**Comment by CavalcanteLeo** [comment]
thanks

**Comment by CavalcanteLeo** [comment]
> plugin:
> 
> ```
> import Vue from 'vue'
> import VueHtml2pdf from 'vue-html2pdf'
> Vue.use(VueHtml2pdf)
> ```
> 
> nuxt.config.js
> 
> ```
>   plugins: [
>     '@/plugins/antd-ui',
>     { src: '@/plugins/vue-apexcharts', ssr: false },
>     { src: '@/plugins/vue-html2pdf', ssr: false }
>   ]
> ```
> 
> somehow, sometimes works but most of the time the page freezes, and sometimes shows an error: window is not defined, even i use `</no-ssr>
