### ISSUE TITLE
Practical question : how it works the "paginate-elements-by-height" property ?

### ISSUE THREAD

**Issue by bArraxas** [kempsteven/vue-html2pdf#14]
Hello,

I'm not sure to understand the operation of "paginate-elements-by-height" property.
I have a page of 2424px of height containing some "&lt;section&gt;" :

section 1 : '121px' of height
section 2 : '495px' of height
section 3 : '311px' of height
section 4 : '84px' of height
section 5 : '156px' of height
section 6 : '553px' of height
section 7 : '455px' of height

(I had too some margins between sections ~ '250px')

My question is what value put in "paginate-elements-by-height" ?

An alternative question, is it possible to force all sections to be on a separate page ? Something like "page-break: auto" ?

Thanks for your help,
Regards

**Comment by kempsteven** [comment]
Lets say you set the value of `paginate-elements-by-height` to **650**, that means per page you will have a maximum of  height of `650px` .


The script will loop through each sections, and add their height + margin top + margin bottom.

So lets take your sample sections into the example, it will work something like this:

section 1 : '121px' of height
section 2 : '495px' of height
section 3 : '311px' of height
section 4 : '84px' of height

let **currentPageHeight** = 0

**1st loop:**
const **sectionHeight** = (section1 height) + (section1 margin top) + (section1 margin bottom)

`// currentPageHeight = 0`
`// sectionHeight = 121`

- Check if (**currentPageHeight** + **sectionHeight**)  <= `650`
        If **true**:
        1.)  **currentPageHeight** = **currentPageHeight** + **sectionHeight**
        2.)  Add the section to **page 1**
        3.)  Go to next loop
        if **false**:
        1.)  currentPageHeight =  sectionHeight
        2.)  Add the section to **page 2**
        3.)  Go to next loop

**The condition will be **TRUE**, since 0 + 121 <= 650**, it will proceed with the steps in the **true** section

**2nd loop:**
const **sectionHeight** = (section2 height) + (section2 margin top) + (section2 margin bottom)
`// currentPageHeight = 121 `
`// sectionHeight = 495`
- Check if (**currentPageHeight** + **sectionHeight**)  <= `650`
        If **true**:
        1.)  **currentPageHeight** = **currentPageHeight** + **sectionHeight**
        2.)  Add the section to **page 1**
        3.)  Go to next loop
        if **false**:
        1.)  currentPageHeight =  sectionHeight
        2.)  Add the section to **page 2**
        3.)  Go to next loop

**The condition will be **TRUE**, since 121 + 495 <= 650**, it will proceed with the steps in the **true** section

**3rd loop:**
const **sectionHeight** = (section3 height) + (section3 margin top) + (section3 margin bottom)
`// currentPageHeight = 616 `
`// sectionHeight = 311`
- Check if (**currentPageHeight** + **sectionHeight**)  <= `650`
        If **true**:
        1.)  **currentPageHeight** = **currentPageHeight** + **sectionHeight**
        2.)  Add the section to **page 1**
        3.)  Go to next loop
        if **false**:
        1.)  currentPageHeight =  sectionHeight
        2.)  Add the section to **page 2**
        3.)  Go to next loop

**The condition will be **FALSE**, since 616 + 311<= 650**, it will proceed with the steps in the **false** section

**4th loop:**
const **sectionHeight** = (section4 height) + (section4 margin top) + (section4 margin bottom)
`// currentPageHeight = 311`
`// sectionHeight = 84 `
- Check if (**currentPageHeight** + **sectionHeight**)  <= `650`
        If **true**:
        1.)  **currentPageHeight** = **currentPageHeight** + **sectionHeight**
        2.)  Add the section to **page 2**
        3.)  Go to next loop
        if **false**:
        1.)  currentPageHeight =  sectionHeight
        2.)  Add the section to **page 3**
        3.)  Go to next loop

**The condition will be **TRUE**, since 311+ 84 <= 650**, it will proceed with the steps in the **true** section

**For your alternative question:**
Lets say you set the value of `paginate-elements-by-height` to **650** again, just set all your sections to `height: 650px` it will let your whole section take a whole page.

I will soon make an easier way to for page breaks, same as html2pdf.js [page breaks](https://www.npmjs.com/package/html2pdf.js/v/0.9.0#page-breaks), since this package uses html2pdf.js under-the-hood

**Comment by marcodeluca** [comment]
Hey, nice package has helped me use jsPDF in our project. 

Having issues with page break and top/bottom margins though. Any update on the page break feature? Been playing with this for an hour and no matter what I try between sections, styles and paginate-elements-by-height, my dynamic content will sometimes get split in bad places (like a single word or sentence on the next page) and without being able to set margins, the breaks are right at the edge of the page.

**Comment by kempsteven** [comment]
Hey, im a bit busy but I might get it done within this week i presume.

**Comment by kempsteven** [comment]
Hey, The page breaks is now available on version 1.6.0
You can also disable the automatic pagination by enabling the prop `manual-pagination`

Here is the [documentation](https://www.npmjs.com/package/vue-html2pdf#page-break)

**Comment by bArraxas** [comment]
Great job !
the previous version (1.3) was buged, i had all tryed but sometimes the script run at infinite (100% processor activity) without render any pdf :(
This version (1.6) never bug what i seen !

It's just in console you (or html2pdf) forgot to disabled the "trace mode" 😄
