### ISSUE TITLE
Page Break works great - still can't get margin's right.

### ISSUE THREAD

**Issue by marcodeluca** [kempsteven/vue-html2pdf#16]
Hey, thanks for the 1.6.0 update, page break works great. Still can't get margins right though. Any suggestions how how to get better top/bottom margins:

![Screen Shot 2020-07-15 at 12 49 57 PM](https://user-images.githubusercontent.com/968926/87573290-b0b2ea00-c69a-11ea-82a6-1c681b08d055.png)

I've tried playing with the data options, but the below does nothing:

```
 htmlToPdfOptions: {
                //margin: 0,
                margin: {
                  top: 0,
                  bottom: 60,
                  left: 0
                },
```

and I've also tried using CSS, but that just breaks the page break entirely where text disappears in between the pages:

![Screen Shot 2020-07-15 at 1 01 46 PM](https://user-images.githubusercontent.com/968926/87573780-6c741980-c69b-11ea-8d04-f1e0b5887298.png)

**Comment by kempsteven** [comment]
Hey, You should use an array instead of an object for margin

**Sample:**
```
// margin: [top, left, bottom, right]
// As for your sample it should be

margin: [0, 0, 60, 0]
```
https://www.npmjs.com/package/vue-html2pdf#html-to-pdf-options

If that still doesn't work, you could use a padding style on that overlapping element instead or use a page break above that paragraph that is overlapping.

**Comment by marcodeluca** [comment]
Yah unfortunately the margin has no effect even fixing it as an array. And using padding causes text to "disappear" in the crack. The issue is this is dynamically generated text. I cannot easily add page breaks without doing the height calculations that html2pdf is doing. Seems like it should be easy to define the height of the page with appropriate top/bottom margins, i just don't understand why I can't.

**Comment by kempsteven** [comment]
So I tried recreating what you did, I created a pdf content with one child element inside it. Inside the child element contains an estimated of 1000 words. Here is the [sample](https://pastebin.com/hGcN3NLc)

I used the margin with a value of 0.3 for bottom
`margin: [0, 0, 0.3, 0],`

It worked perfectly it did what it supposed to do with the page, here is the sample:
![image](https://user-images.githubusercontent.com/51051704/87672794-10e28280-c7a6-11ea-9c33-70ac99012a50.png)

Here is a sample of my component:
https://pastebin.com/LjabFpdK

If things still doesn't work out, Could you give me a sample of your component and a sample of the dynamically generated text or an equivalent sample text? So that I could debug it on my side

**Comment by kempsteven** [comment]
Feel free to open this, if the issue persist!
