### ISSUE TITLE
How I can add footer with page numbers and date?

### ISSUE THREAD

**Issue by TargiX** [kempsteven/vue-html2pdf#30]
Hi, thanks for you great work, I want to add footer with date and current page. I see that this is possible with html2pdf [https://github.com/eKoopmans/html2pdf.js/issues/21#issuecomment-447028134](https://github.com/eKoopmans/html2pdf.js/issues/21#issuecomment-447028134) , but how I can do it with this plugin?

**Comment by kempsteven** [comment]
Hey, thank you for appreciating my work.
Hmm I was not aware we could do that with html2pdf.js, so unfortunately we don't have that feature as for now.
I will mark this as an enhancement and maybe work on this on this weekend or next week.

**Comment by moktc** [comment]
Hi I am also looking for the ability to add header and footer to the page. Thanks.

**Comment by kempsteven** [comment]
Hi @moktc , will add that enhancement in maybe a few days or a week.

**Comment by kempsteven** [comment]
Pagination and headers can now be achieved in version 1.8.0. Be also careful since I have changed a few event names see details [here](https://www.npmjs.com/package/vue-html2pdf#migrating-from-17x-to-18x-and-so-on).

I created an event called `@beforeDownload`, the event arguments are `html2pdf.js`, `option`s, and `pdfContent`. Now you can have the full control of the html2pdf.js's API.

Here is the sample use-case of @beforeDownload
https://www.npmjs.com/package/vue-html2pdf#sample-use-case-of-beforedownload

Ill be closing this now, if you have another issue feel free open a new one :)
