### ISSUE TITLE
vue-html2pdf not working in pad/mobile view on Chrome.

### ISSUE THREAD

**Issue by sujandev** [kempsteven/vue-html2pdf#49]
**Describe the bug**
its working on Safari and firefox view but when i tried to open it on Chrome ipad or mobile view it just show a blank area of the content . plz see the attached image.

Google Chrome is up to date
Version 87.0.4280.88 (Official Build) (x86_64)

**Screenshots**
![invoice bug](https://user-images.githubusercontent.com/9714570/101462550-8a059080-3966-11eb-9cbd-0eb375b72d19.jpeg)

**Package Version**
"vue-html2pdf": "^1.8.0",

**Comment by kempsteven** [comment]
So it doesn't work on Chrome for Andriod and IOS? and works in Chrome for windows?

**Comment by sujandev** [comment]
> So it doesn't work on Chrome for Andriod and IOS? and works in Chrome for windows?

**Comment by sujandev** [comment]
i checked  from mac. what i am trying to say is  all working in desktop view. but when i try in mobile view from my desktop chrome ( browser mobile view  not from mobile ) using device toolbar by inspecting desktop browser its output is blank.

**Comment by abdulmlik** [comment]
I have the same problem now...
if it has been solved? Can I get the solution?

**Comment by carcormir** [comment]
Hey! @kempsteven This issue was closed but I am currently having the exact same issue as @sujandev 
Any suggestions on how to fix it?
Basically, when testing on mobile, the modal is transparent and does not show the content (as explained in this issue). 
It happens in chrome, edge, firefox and safari for the latest versions
