### ISSUE TITLE
Textarea content is not visible

### ISSUE THREAD

**Issue by 3bu1** [kempsteven/vue-html2pdf#50]
Textarea content is not completely visible

Showing in PDF like this
![image](https://user-images.githubusercontent.com/6350331/102113321-e7b24500-3e5e-11eb-8700-197a3b05ecc6.png)

Actual content like this
![image](https://user-images.githubusercontent.com/6350331/102113531-2647ff80-3e5f-11eb-8e94-ad8aa218d16d.png)

Others Who faced same issue:
https://github.com/kempsteven/vue-html2pdf-demo/issues/12

Any suggetions.

**Comment by kempsteven** [comment]
Let me get back to you after I replicate it

**Comment by 3bu1** [comment]
Hi @kempsteven any update on this, where you able to replicate?

**Comment by kempsteven** [comment]
Hello, I apologize was too busy, anyways this is an on going issue with html2canvas, which is part of html2pdf.js.

See here one of the ongoing issue in html2canvas: https://github.com/niklasvh/html2canvas/issues/2008

I recommend just using a div which is editable rather than a textarea, with the right css I believe that should look like a textarea.

more about the editable div here:
https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content

Sample of editable div
```
<div contenteditable="true">
  This text can be edited by the user.
</div>
```

I believe that should work, but I have not tested it yet.

**Comment by 3bu1** [comment]
thanks @kempsteven . For time being will follow your suggetion.

**Comment by 3bu1** [comment]
Finally figured out the issue, It is due to floats. Page breaks and floats cannot co-exist.
